repos:
-   repo: https://github.com/lorenzwalthert/pre-commit-hooks
    rev: v0.0.0.9027
    hooks:
    -   id: style-files
        args: [--style_fun=tidyverse_style]
    -   id: parsable-R
    -   id: lintr
    -   id: no-browser-statement
    -   id: readme-rmd-rendered
    #-   id: roxygenize
    -   id: use-tidy-description
